/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const Statistics = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'activeMinutes' : IDL.Nat,
  'created' : Time,
  'calorieIntakeAvg' : IDL.Int,
  'heightCm' : IDL.Int,
  'userId' : UserId,
  'weightKg' : IDL.Int,
});
export const WorkoutLog = IDL.Record({
  'id' : IDL.Text,
  'userId' : UserId,
  'exercises' : IDL.Vec(IDL.Text),
  'durationMinutes' : IDL.Nat,
  'timestamp' : Time,
  'repetitions' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'getAllStats' : IDL.Func([], [IDL.Vec(Statistics)], ['query']),
  'getAllWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getStats' : IDL.Func([UserId], [IDL.Opt(Statistics)], ['query']),
  'getWorkoutLog' : IDL.Func([IDL.Text], [WorkoutLog], ['query']),
  'saveStats' : IDL.Func([Statistics], [], []),
  'saveWorkoutLog' : IDL.Func([WorkoutLog], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const Statistics = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'activeMinutes' : IDL.Nat,
    'created' : Time,
    'calorieIntakeAvg' : IDL.Int,
    'heightCm' : IDL.Int,
    'userId' : UserId,
    'weightKg' : IDL.Int,
  });
  const WorkoutLog = IDL.Record({
    'id' : IDL.Text,
    'userId' : UserId,
    'exercises' : IDL.Vec(IDL.Text),
    'durationMinutes' : IDL.Nat,
    'timestamp' : Time,
    'repetitions' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'getAllStats' : IDL.Func([], [IDL.Vec(Statistics)], ['query']),
    'getAllWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getStats' : IDL.Func([UserId], [IDL.Opt(Statistics)], ['query']),
    'getWorkoutLog' : IDL.Func([IDL.Text], [WorkoutLog], ['query']),
    'saveStats' : IDL.Func([Statistics], [], []),
    'saveWorkoutLog' : IDL.Func([WorkoutLog], [], []),
  });
};

export const init = ({ IDL }) => { return []; };