/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Statistics {
  'id' : string,
  'bio' : string,
  'activeMinutes' : bigint,
  'created' : Time,
  'calorieIntakeAvg' : bigint,
  'heightCm' : bigint,
  'userId' : UserId,
  'weightKg' : bigint,
}
export type Time = bigint;
export type UserId = Principal;
export interface WorkoutLog {
  'id' : string,
  'userId' : UserId,
  'exercises' : Array<string>,
  'durationMinutes' : bigint,
  'timestamp' : Time,
  'repetitions' : Array<bigint>,
}
export interface _SERVICE {
  'getAllStats' : ActorMethod<[], Array<Statistics>>,
  'getAllWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getStats' : ActorMethod<[UserId], [] | [Statistics]>,
  'getWorkoutLog' : ActorMethod<[string], WorkoutLog>,
  'saveStats' : ActorMethod<[Statistics], undefined>,
  'saveWorkoutLog' : ActorMethod<[WorkoutLog], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];